/**
 * Alert Store
 *
 * In-memory storage for risk alerts generated by the autonomous agent.
 * Provides query API for the alert server endpoint.
 * Retains the last 1000 alerts with automatic pruning.
 */

export interface RiskAlert {
  id: string;
  address: string;
  riskScore: number;
  riskLevel: string;
  confidenceLevel: 'low' | 'medium' | 'high';
  txHash: string;
  reportHash: string;
  blockNumber: number;
  timestamp: string;
  keyFindings: string[];
  breakdown: {
    contract_risk: number;
    behavior_risk: number;
    reputation_risk: number;
  };
  explorerUrl: string;
}

const MAX_ALERTS = 1000;

export class AlertStore {
  private alerts: RiskAlert[] = [];

  add(alert: RiskAlert): void {
    this.alerts.unshift(alert);
    if (this.alerts.length > MAX_ALERTS) {
      this.alerts = this.alerts.slice(0, MAX_ALERTS);
    }
  }

  getAll(): RiskAlert[] {
    return this.alerts;
  }

  getRecent(limit = 50): RiskAlert[] {
    return this.alerts.slice(0, limit);
  }

  getByAddress(address: string): RiskAlert[] {
    const normalized = address.toLowerCase();
    return this.alerts.filter((a) => a.address.toLowerCase() === normalized);
  }

  getByRiskLevel(level: string): RiskAlert[] {
    return this.alerts.filter((a) => a.riskLevel.toLowerCase() === level.toLowerCase());
  }

  getHighRisk(): RiskAlert[] {
    return this.alerts.filter((a) => a.riskScore >= 67);
  }

  count(): number {
    return this.alerts.length;
  }

  stats(): {
    total: number;
    high: number;
    medium: number;
    low: number;
    lastAlert: string | null;
  } {
    return {
      total: this.alerts.length,
      high: this.alerts.filter((a) => a.riskScore >= 67).length,
      medium: this.alerts.filter((a) => a.riskScore >= 34 && a.riskScore < 67).length,
      low: this.alerts.filter((a) => a.riskScore < 34).length,
      lastAlert: this.alerts.length > 0 ? this.alerts[0].timestamp : null,
    };
  }
}
